### PR TITLE
add code to plot neutcurves

### PR DESCRIPTION
**Pull request by jbloom**
@aminaddetia @tylernstarr, I wrote code that plots what I think should be the neut curves and Fig 1C.

To do this, I used @aminaddetia's nicely organized rough plots on computational notebooks.

I then made a subdirectory `exptl_neut_data` in this repo, and into `data` I just copied the fraction infectivity CSVs. I then added a notebook in `exptl_neut_data` that reads in these data and makes the two following plots.

Here is what I suggest for Fig 1C:
Screen Shot 2020-11-27 at 1 16 54 PM

And for Fig S3:
Screen Shot 2020-11-27 at 1 17 04 PM

Both of these plots are automatically made by the notebook, so it should be easy to update them once we've corrected the concentrations. Any opinions on these?

### CODE REVIEW

**Comment by tylernstarr** [comment]
Looks really nice! I'll approve but leave in case @aminaddetia has additional comments.

Do you think it's important to show actual IC50s versus fold-change relative to WT? (Fold change is what we showed in the Crowe lab paper validations). The actual IC50 is interesting to know about, but at the same time there would be less mental effort to re-scale between sub-panels, figure out why the one line is shifting, etc. if they were all just standardized to 1 for fold change.

**Review by tylernstarr — APPROVED** [review]

**Comment by jbloom** [comment]
Good suggestion, I just added another pull request that makes it fold-change in IC50 instead. See here:
Screen Shot 2020-11-27 at 1 43 53 PM

**Comment by tylernstarr** [comment]
I like the fold!

I think it's probably not needed on this plot, but curious -- is it right that for the REGN-COV2 cocktial neuts, we do expect the three single-Ab escape muts to have ~2-fold decreases in neut? (Would be exactly 2 I think if the individual mAbs have identical IC50 alone, which seems to be close to the case). If that's the case, it could be interseting to plot a y=2 line just on the cocktails plot, but perhaps too much effort to add/explain than it's worth. But I do think it's striking that the single muts hit that expectation bang-on, it seems. Overall, very nice validations!

**Comment by jbloom** [comment]
Agreed, I am going to merge now and then we can update more later on another branch with @aminaddetia's comments.

**Pull request merged**
