### PR TITLE
add preprint links

### PR DESCRIPTION
**Pull request by tylernstarr**
PR adds link to preprint on the base readme, the dms-view metadata section, and the dms-view landing pad. Once merged, I will check all three links work

### CODE REVIEW

**Review by jbloom — CHANGES_REQUESTED** [review]
@tylernstarr, should we link pre-print rather than Tweet thread? Wasn't sure if you put Tweets intentionally or accidentally?

**Comment by tylernstarr** [comment]
Whoops, definitely mistake. Will update now

**Comment by tylernstarr** [comment]
should be fixed now. glad _somebody's_ paying attention...

**Review by jbloom — APPROVED** [review]

**Comment by tylernstarr** [comment]
checked updated links, looks good

**Pull request merged**
